# Generated by Django 4.2.1 on 2023-06-13 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('Sudurpaschim', 'Sudurpaschim'), ('Karnali Province', 'Karnali Province'), ('Lumbini Province', 'Lumbini Province'), ('Gandaki Province', 'Gandaki Province'), ('Bagmati Province', 'Bagmati Province'), ('Madesh Province', 'Madesh Province'), ('Province 1', 'Province 1')], max_length=100)),
                ('district_name', models.CharField(max_length=100)),
                ('district_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DistrictImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='static/uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_desc', models.TextField()),
                ('event_image', models.FileField(null=True, upload_to='static/uploads/events')),
                ('event_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='static/uploads/location')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('location_desc', models.TextField()),
                ('best_season', models.CharField(choices=[('any', 'any'), ('spring', 'spring'), ('summer', 'summer'), ('autumn', 'autumn'), ('winter', 'winter')], default='any', max_length=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_data.district')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_data.events')),
            ],
        ),
    ]
