# Generated by Django 4.2.1 on 2023-06-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_data', '0003_alter_location_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='event',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_images',
        ),
        migrations.AddField(
            model_name='location',
            name='location_image',
            field=models.FileField(null=True, upload_to='static/uploads/location'),
        ),
    ]
