# Generated by Django 4.2.1 on 2023-06-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_data', '0006_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='province_desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
